### ISSUE TITLE
Dimension of output tensors in eval_pascal.py not match

### ISSUE THREAD

**Issue by wyxhhh** [valeoai/zero_shot_semantic_segmentation#3]
Hi,
When I was running eval_pascal.py, an error occured
```
Traceback (most recent call last): 
File "eval_pascal.py", line 166, in validation
all_target = np.concatenate(all_target)
File "<__array_function__ internals>", line 6, in concatenate 
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 700 and the array at index 1 has size 765
```
I tried to output ```target.shape``` for all elements in ```all_target``` and the dimensions vary a lot

**Comment by maximebucher** [comment]
Hi,
that was dead code, I updated the file.
Maxime
